--===============================================================================
--Magnitude Analysis
--===============================================================================

-- Find total customers by cities 
Select 
City ,
Count(Order_Id) As Total_Orders
From sales.orders
Group By City
Order By 2 Desc

-- Find total customers by gender
Select 
Gender,
Count(Gender) As Total_Customers
From sales.orders
Group By Gender
Order BY 2

-- Find total subcatgories by category 
Select 
Category,
Count(Distinct Subcategory) As Total_Subcategory
From sales.orders
Group By Category


--- What is the average Revenue in each category?
Select 
Category,
Round(Avg(Total_Price),2) As Total_Revenue
From sales.orders
Group BY category

-- What is the total revenue generated for each category?
Select 
Category,
Round(Sum(Total_Price),2) As Total_Revenue
From sales.orders
Group BY Category


-- What is the total revenue generated by each customer?
Select 
Concat(First_Name,' ',Last_Name) As Full_name,
Round(Sum(Total_Price),2) As Total_Revenue
From sales.orders
Group By Concat(First_Name,' ',Last_Name)

----- What is the distribution of sold items across cities?
Select 
City,
Round(Sum(Total_Price),2) As Total_Quantity 
From sales.orders
Group By City
Order By 2

------ What is the distribution  of  Payment_Method?
Select 
Payment_Method,
Count(Payment_Method) Total_Payment_Count
From sales.orders
Group BY Payment_Method
Order By Total_Payment_Count Desc
Select * From sales.orders

----- What is the Total Revenue By Weather ?
Select 
Weather,
Round(Sum(Total_Price),2) As Total_Revenue
From sales.orders
Group BY Weather
Order By 2 Desc

---- What is the  Total Revenue by Order Type? 
Select 
Order_Type,
Round(Sum(Total_Price),2) As Total_Revenue
From Sales.orders
Group BY Order_Type
Order By 2 Desc
