/*
===============================================================================
Part-to-Whole Revenue Analysis by Category
===============================================================================
Purpose:
    - Calculate total revenue generated by each category.
    - Determine the percentage share of each category in the overall revenue.
    - Identify top-performing categories for strategic decisions (e.g., marketing focus, stock prioritization).

SQL Functions Used:
    - SUM(): Aggregates total sales values by category.
    - ROUND(): Formats numerical values for better readability.
    - SUM() OVER(): Calculates total revenue across all categories (window function).
========================================================================================*/

With Cateories_Summary As (
Select 
    Category,
    Round(Sum(Total_Price),2) As Total_Revenue
From sales.orders
Group By 
    Category
) 

Select 
    Category,
    Total_Revenue,
    Sum(Total_Revenue) Over() Overall_Revenue,
    Round((Total_Revenue/Sum(Total_Revenue) Over()),2) *100 As Percentage_of_Total
From Cateories_Summary
Order By 
    Round((Total_Revenue/Sum(Total_Revenue) Over()),2) *100 DESC

/*===============================================================================
Customer Payment Method Preference Analysis
===============================================================================
Purpose:
    - Identify the most frequently used payment method by customers.
    - Determine the percentage share of each payment method in total transactions.
    - Useful for improving checkout options and understanding customer behavior.
==================================================================================*/

With Payment_Summary As 
( 
Select 
    Payment_Method,
    Count(Payment_Method ) Total_Payment
From sales.orders
Group By
    Payment_Method
) 

Select 
    Payment_Method,
    Total_Payment,
    Sum(Total_Payment) Over() Overall_Payments,
    (Cast(Total_Payment As Float) /Sum(Total_Payment) Over()) *100 Percentage_Of_Total
From Payment_Summary
Order By 2 Desc

/*===============================================================================
Order Distribution by Weather Conditions
===============================================================================
Purpose:
    - Analyze how different weather conditions impact order volume.
    - Calculate the percentage of total orders occurring under each weather condition.
    - Useful for demand forecasting, staffing, and promotional planning.
===============================================================================
*/


Select 
	Weather,
	Total_Orders,
	Sum(Total_Orders) Over() Overall_Orders,
	(Cast(Total_Orders As Float) /Sum(Total_Orders) Over())*100 As Percentage_of_Total
From 
(
	Select 
		Weather,
		Count(*) As Total_Orders
	From sales.orders
	Group By
		Weather
)t
